
expected_out_examples_no_tools = {'claude-3-5-sonnet-20241022': {'id': 'msg_011WH7cvyM9LGa87nsu3dQ6P',
  'type': 'message',
  'role': 'assistant',
  'model': 'claude-3-5-sonnet-20241022',
  'content': [{'type': 'text',
    'text': "The capital of Ireland is Dublin.\n\nFun fact: The St. James's Gate Brewery in Dublin, where Guinness was first brewed in 1759, signed a 9,000-year lease for its property. The lease was signed by Arthur Guinness for an annual rent of £45. The brewery is still operating today and is one of Ireland's most popular tourist attractions!"}],
  'stop_reason': 'end_turn',
  'stop_sequence': None,
  'usage': {'input_tokens': 20,
   'cache_creation_input_tokens': 0,
   'cache_read_input_tokens': 0,
   'output_tokens': 85}},
 'gemini-1.5-flash': {'candidates': [{'content': {'parts': [{'text': 'The capital of Ireland is Dublin.\n\nFun fact: Dublin is home to the Guinness Storehouse, a seven-story building dedicated to the famous stout, which offers panoramic views of the city from its Gravity Bar.\n'}],
     'role': 'model'},
    'finishReason': 'STOP',
    'avgLogprobs': -0.17427449876611883}],
  'usageMetadata': {'promptTokenCount': 14,
   'candidatesTokenCount': 44,
   'totalTokenCount': 58},
  'modelVersion': 'gemini-1.5-flash'},
 'gpt-4o-2024-08-06': {'id': 'chatcmpl-AuI122vSUmCiQXrfXTOLub17qdkre',
  'object': 'chat.completion',
  'created': 1737978984,
  'model': 'gpt-4o-2024-08-06',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': 'The capital of Ireland is Dublin. A fun fact about Dublin is that it is home to the oldest pub in Ireland, The Brazen Head, which dates back to 1198.',
     'refusal': None},
    'logprobs': None,
    'finish_reason': 'stop'}],
  'usage': {'prompt_tokens': 20,
   'completion_tokens': 38,
   'total_tokens': 58,
   'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'audio_tokens': 0,
    'accepted_prediction_tokens': 0,
    'rejected_prediction_tokens': 0}},
  'service_tier': 'default',
  'system_fingerprint': 'fp_4691090a87'},
 'gpt-4o-mini': {'id': 'chatcmpl-AuI13u6jiLtjN5AS6Guu1XIjhrwgZ',
  'object': 'chat.completion',
  'created': 1737978985,
  'model': 'gpt-4o-mini-2024-07-18',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': 'The capital of Ireland is Dublin. \n\nOne fun fact about Dublin is that it is home to the famous Guinness Storehouse, where the iconic stout beer is brewed. The Storehouse features an exhibition on the history of Guinness, and visitors can enjoy a pint with a panoramic view of the city from the Gravity Bar!',
     'refusal': None},
    'logprobs': None,
    'finish_reason': 'stop'}],
  'usage': {'prompt_tokens': 20,
   'completion_tokens': 64,
   'total_tokens': 84,
   'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'audio_tokens': 0,
    'accepted_prediction_tokens': 0,
    'rejected_prediction_tokens': 0}},
  'service_tier': 'default',
  'system_fingerprint': 'fp_72ed7ab54c'},
 'cerebras-llama3.1-8b': {'id': 'chatcmpl-47e134c9-db6c-41f7-a433-814f39d29dc9',
  'choices': [{'finish_reason': 'stop',
    'index': 0,
    'message': {'content': "The capital of Ireland is Dublin. \n\nOne fun fact about Ireland: The Blarney Stone, which is located in County Cork near Cork City, is believed to give the gift of eloquence to those who kiss it. The stone has been kissed by millions of people over the centuries, and it's said that if you kiss the Blarney Stone, you'll be able to speak with charm and wit for the rest of your life!",
     'role': 'assistant'}}],
  'created': 1737978987,
  'model': 'llama3.1-8b',
  'system_fingerprint': 'fp_6381a6c109',
  'object': 'chat.completion',
  'usage': {'prompt_tokens': 49, 'completion_tokens': 90, 'total_tokens': 139},
  'time_info': {'queue_time': 0.000234863,
   'prompt_time': 0.003085407,
   'completion_time': 0.043706937,
   'total_time': 0.04857802391052246,
   'created': 1737978987}},
 'deepseek-chat': {'id': 'fa1b77a8-bca6-4f1b-9e29-b1037cd95813',
  'object': 'chat.completion',
  'created': 1737978987,
  'model': 'deepseek-chat',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': "The capital of Ireland is **Dublin**.\n\n**Fun Fact:** Dublin is home to the **Book of Kells**, a stunningly illuminated manuscript of the four Gospels of the New Testament, created by Celtic monks around 800 AD. It is housed in the Old Library at Trinity College Dublin and is considered one of Ireland's greatest cultural treasures!"},
    'logprobs': None,
    'finish_reason': 'stop'}],
  'usage': {'prompt_tokens': 17,
   'completion_tokens': 69,
   'total_tokens': 86,
   'prompt_tokens_details': {'cached_tokens': 0},
   'prompt_cache_hit_tokens': 0,
   'prompt_cache_miss_tokens': 17},
  'system_fingerprint': 'fp_3a5770e1b4'},
 'groq-llama-3.3-70b-versatile': {'id': 'chatcmpl-f0e69a2a-67a5-49cc-8f37-b38c480711f5',
  'object': 'chat.completion',
  'created': 1737978990,
  'model': 'llama-3.3-70b-versatile',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': "The capital of Ireland is Dublin. \n\nHere's a fun fact: Dublin is home to the Guinness Storehouse, a seven-story building that tells the story of Ireland's iconic stout. It's one of Ireland's most popular attractions, and at the top, you can even pour your own perfect pint of Guinness at the rooftop bar, Gravity!"},
    'logprobs': None,
    'finish_reason': 'stop'}],
  'usage': {'queue_time': 0.02357848,
   'prompt_tokens': 49,
   'prompt_time': 0.009425489,
   'completion_tokens': 70,
   'completion_time': 0.254545455,
   'total_tokens': 119,
   'total_time': 0.263970944},
  'system_fingerprint': 'fp_4e32347616',
  'x_groq': {'id': 'req_01jjksxkt6fj4byfrz6zygtw7r'}}}



expected_out_examples_with_tools = {'claude-3-5-sonnet-20241022': {'type': 'error',
  'error': {'type': 'invalid_request_error',
   'message': 'tools.0.custom.input_schema: Field required'}},
 'gemini-1.5-flash': {'error': {'code': 400,
   'message': 'Invalid JSON payload received. Unknown name "temperature": Cannot find field.',
   'status': 'INVALID_ARGUMENT',
   'details': [{'@type': 'type.googleapis.com/google.rpc.BadRequest',
     'fieldViolations': [{'description': 'Invalid JSON payload received. Unknown name "temperature": Cannot find field.'}]}]}},
 'gpt-4o-2024-08-06': {'id': 'chatcmpl-AuIy7Hlo7M1dqrQJKQj7ya2SoOO5h',
  'object': 'chat.completion',
  'created': 1737982647,
  'model': 'gpt-4o-2024-08-06',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': None,
     'tool_calls': [{'id': 'call_CUjkups6oTZrK7IoKSdlQgo6',
       'type': 'function',
       'function': {'name': 'get_weather',
        'arguments': '{"city":"dublin","date":"2023-10-27"}'}}],
     'refusal': None},
    'logprobs': None,
    'finish_reason': 'tool_calls'}],
  'usage': {'prompt_tokens': 82,
   'completion_tokens': 25,
   'total_tokens': 107,
   'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'audio_tokens': 0,
    'accepted_prediction_tokens': 0,
    'rejected_prediction_tokens': 0}},
  'service_tier': 'default',
  'system_fingerprint': 'fp_4691090a87'},
 'gpt-4o-mini': {'id': 'chatcmpl-AuIy9IpKcwX1DG4zD3UKwZdliYVch',
  'object': 'chat.completion',
  'created': 1737982649,
  'model': 'gpt-4o-mini-2024-07-18',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': None,
     'tool_calls': [{'id': 'call_0KPgsQaaso8IXPUpG6ktM1DC',
       'type': 'function',
       'function': {'name': 'get_weather',
        'arguments': '{"city":"Dublin","date":"2023-10-07"}'}}],
     'refusal': None},
    'logprobs': None,
    'finish_reason': 'tool_calls'}],
  'usage': {'prompt_tokens': 82,
   'completion_tokens': 25,
   'total_tokens': 107,
   'prompt_tokens_details': {'cached_tokens': 0, 'audio_tokens': 0},
   'completion_tokens_details': {'reasoning_tokens': 0,
    'audio_tokens': 0,
    'accepted_prediction_tokens': 0,
    'rejected_prediction_tokens': 0}},
  'service_tier': 'default',
  'system_fingerprint': 'fp_72ed7ab54c'},
 'cerebras-llama3.1-8b': {'id': 'chatcmpl-d128564b-ac4f-469d-bc58-8a30a75a49b3',
  'choices': [{'finish_reason': 'tool_calls',
    'index': 0,
    'message': {'tool_calls': [{'id': '8abbdbc4d',
       'type': 'function',
       'function': {'name': 'get_weather',
        'arguments': '{"city": "dublin", "date": "tomorrow"}'}}],
     'role': 'assistant'}}],
  'created': 1737982649,
  'model': 'llama3.1-8b',
  'system_fingerprint': 'fp_6381a6c109',
  'object': 'chat.completion',
  'usage': {'prompt_tokens': 280,
   'completion_tokens': 17,
   'total_tokens': 297},
  'time_info': {'queue_time': 8.4651e-05,
   'prompt_time': 0.014553496,
   'completion_time': 0.00775826,
   'total_time': 0.023982524871826172,
   'created': 1737982649}},
 'deepseek-chat': {'id': '7b15a943-316a-43f7-b317-946b46f6420c',
  'object': 'chat.completion',
  'created': 1737982650,
  'model': 'deepseek-chat',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': '',
     'tool_calls': [{'index': 0,
       'id': 'call_0_b55d84fe-9ce5-40a4-a1e2-65c9f82bd477',
       'type': 'function',
       'function': {'name': 'get_weather',
        'arguments': '{"city":"Dublin","date":"2023-10-06"}'}}]},
    'logprobs': None,
    'finish_reason': 'tool_calls'}],
  'usage': {'prompt_tokens': 164,
   'completion_tokens': 29,
   'total_tokens': 193,
   'prompt_tokens_details': {'cached_tokens': 128},
   'prompt_cache_hit_tokens': 128,
   'prompt_cache_miss_tokens': 36},
  'system_fingerprint': 'fp_3a5770e1b4'},
 'groq-llama-3.3-70b-versatile': {'id': 'chatcmpl-84ff8170-ec86-41c1-8f30-c3a92c0f073e',
  'object': 'chat.completion',
  'created': 1737982652,
  'model': 'llama-3.3-70b-versatile',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'tool_calls': [{'id': 'call_dphf',
       'type': 'function',
       'function': {'name': 'get_weather',
        'arguments': '{"city": "Dublin", "date": "2024-04-18"}'}}]},
    'logprobs': None,
    'finish_reason': 'tool_calls'}],
  'usage': {'queue_time': 0.02048758,
   'prompt_tokens': 261,
   'prompt_time': 0.055640456,
   'completion_tokens': 26,
   'completion_time': 0.124366268,
   'total_tokens': 287,
   'total_time': 0.180006724},
  'system_fingerprint': 'fp_3884478861',
  'x_groq': {'id': 'req_01jjkxdbspe8es9rwpjx02q83y'}},
 'grok-2-latest': {'id': 'd23f0836-c2bb-4067-90c9-0a69a096bfb9',
  'object': 'chat.completion',
  'created': 1737982652,
  'model': 'grok-2-1212',
  'choices': [{'index': 0,
    'message': {'role': 'assistant',
     'content': 'I am retrieving the weather forecast for Dublin tomorrow.',
     'tool_calls': [{'id': 'call_18966747',
       'function': {'name': 'get_weather',
        'arguments': '{"city":"Dublin","date":"2022-05-15"}'},
       'type': 'function'}],
     'refusal': None},
    'finish_reason': 'tool_calls'}],
  'usage': {'prompt_tokens': 185,
   'completion_tokens': 11,
   'total_tokens': 196,
   'prompt_tokens_details': {'text_tokens': 185,
    'audio_tokens': 0,
    'image_tokens': 0,
    'cached_tokens': 0}},
  'system_fingerprint': 'fp_26e56ab758'}}

from percolate.services.llm.LanguageModel import OpenAIResponseScheme, AnthropicAIResponseScheme, GoogleAIResponseScheme

#TODO: fill in tests

class _ResponseStub:
  def __init__(self, data):
      self.data = data
  def json(self):
    return self.data
  
def test_parses_response_openai():
   
    r = OpenAIResponseScheme.parse(_ResponseStub(expected_out_examples_no_tools['gpt-4o-mini']),sid=None, model_name='gpt-4o-mini')
    assert r.tokens == 84 and r.content == 'The capital of Ireland is Dublin. \n\nOne fun fact about Dublin is that it is home to the famous Guinness Storehouse, where the iconic stout beer is brewed. The Storehouse features an exhibition on the history of Guinness, and visitors can enjoy a pint with a panoramic view of the city from the Gravity Bar!'

def test_parses_response_anthropic():
    AnthropicAIResponseScheme.parse(_ResponseStub(expected_out_examples_no_tools['claude-3-5-sonnet-20241022']),sid=None, model_name='claude-3-5-sonnet-20241022')    

def test_parses_response_google():
    GoogleAIResponseScheme.parse(_ResponseStub(expected_out_examples_no_tools['gemini-1.5-flash']),sid=None, model_name='gemini-1.5-flash')