services:
  postgres:
    image: percolationlabs/postgres-base:16
    container_name: percolate_test2
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "5439:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/percolate_data
      - ./extension/sql:/docker-entrypoint-initdb.d
    restart: unless-stopped

volumes:
  postgres_data:
#if you need to you can export new env vars before up
#export MY_API_KEY=your-api-key-goes-here
#docker compose up -d
