apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: p8
  name: p8
spec:
  #the operator needs to use 16 as a postgres version
  imageName: percolationlabs/postgres-base:16
  instances: 1
  storage:
    size: 10Gi
  #to install percolate from config maps add config maps from scripts folder run:  python gen_sql_install_configmap.py --apply
  #this applies to the p8 namespace by default
  bootstrap:
    initdb:
      database: app
      owner: app
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: 00-install
            key: 00_install.sql
          - name: 01-add-functions
            key: 01_add_functions.sql
          - name: 02-create-primary
            key: 02_create_primary.sql
          - name: 03-create-secondary
            key: 03_create_secondary.sql
          - name: 10-finalize
            key: 10_finalize.sql
            
#kubectl get secret -n p8 percolate-test-app -o json | jq '.data |= map_values(@base64d)'
