apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: percolate
spec:
  #the operator needs to use 16 as a postgres version
  imageName: percolationlabs/postgres-base:16
  instances: 1
  storage:
    size: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percolate-api
  #namespace: percolate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: percolate-api
  template:
    metadata:
      labels:
        app: percolate-api
    spec:
      containers:
        - name: percolate-api
          image: percolationlabs/percolate-api
          ports:
            - containerPort: 5008
          env:
            # do do from secret
            # - name: P8_PG_PASSWORD
            #   value: "??"
            - name: P8_PG_PORT
              value: "5432"
            - name: P8_PG_USER
              value: "app"
            - name: P8_PG_HOST
              value: "percolate-one-rw.percolate.svc.cluster.local"
          # envFrom:
          #   - configMapRef:
          #       name: percolate-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: percolate-api
  #namespace: percolate
spec:
  selector:
    app: percolate-api
  ports:
    - protocol: TCP
      port: 5008
      targetPort: 5008
  type: ClusterIP