#by default this will but everything in the p8 namespace and create that namespace
#if not put here, then we need to configure P8_PG_HOST for the app
apiVersion: v1
kind: Namespace
metadata:
  name: p8
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  namespace: p8
  name: percolate-test
spec:
  #the operator needs to use 16 as a postgres version
  imageName: percolationlabs/postgres-base:16
  instances: 1
  storage:
    size: 10Gi
  #to install percolate from config maps add config maps from scripts folder run:  python gen_sql_install_configmap.py --apply
  #this applies to the p8 namespace by default
  bootstrap:
    initdb:
      postInitApplicationSQLRefs:
        configMapRefs:
          - name: 00-install
            key: 00_install.sql
          - name: 01-add-functions
            key: 01_add_functions.sql
          - name: 02-create-primary
            key: 02_create_primary.sql
          - name: 03-create-secondary
            key: 03_create_secondary.sql
          - name: 10-finalize
            key: 10_finalize.sql
#make sure to set a strorage class in your cloud
#for example in hetnzer kubectl apply -f https://raw.githubusercontent.com/hetznercloud/csi-driver/master/deploy/kubernetes/hcloud-csi.yml

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: p8
  name: percolate-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "percolate-api"
  template:
    metadata:
      labels:
        app: percolate-api
    spec:
      containers:
        - name: percolate-api
          image: percolationlabs/percolate-api
          imagePullPolicy: Always
          ports:
            - containerPort: 5008
          env:
            #load the secret from the percolate cluster
            - name: P8_PG_PASSWORD
              valueFrom:
                secretKeyRef:
                  #this is the name of the pg database and the secret corresponding
                  name: percolate-app
                  key: password
            - name: P8_PG_PORT
              value: "5432"
            - name: P8_PG_USER
              value: "app"
            - name: P8_PG_HOST
              value: "percolate-rw.p8.svc.cluster.local"
          # envFrom:
          #   - configMapRef:
          #       name: percolate-env
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: percolate-api
  namespace: p8
spec:
  selector:
    app: percolate-api
  ports:
    - protocol: TCP
      port: 5008
      targetPort: 5008
  type: ClusterIP