apiVersion: v1
kind: Service
metadata:
  name: percolate-media-api
  namespace: eepis
spec:
  selector:
    app: percolate-media-api
  ports:
  - port: 5008
    targetPort: 5008
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: percolate-media-api
  namespace: eepis
spec:
  replicas: 5
  selector:
    matchLabels:
      app: percolate-media-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: percolate-media-api
    spec:
      tolerations:
      - key: "node.kubernetes.io/unschedulable"
        operator: "Exists"
        effect: "NoSchedule"
      containers:
      - name: percolate-media-api
        image: percolationlabs/percolate-api:media
        imagePullPolicy: Always
        ports:
        - containerPort: 5008
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 512Mi 
        envFrom:
        - configMapRef:
            name: percolate-env
        env:
        - name: TUS_STORAGE_PATH
          value: "/tmp/tus-uploads"  
        - name: TUS_USE_S3
          value: "true"
        - name: TUS_DIRECT_S3
          value: "true"   